# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 20:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('charge_id', models.CharField(blank=True, max_length=32, null=True)),
                ('delivery_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude')),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('radius', models.FloatField(default=10)),
                ('open_hour', models.IntegerField(default=8)),
                ('close_hour', models.IntegerField(default=6)),
                ('item', models.CharField(max_length=50)),
                ('unit_price', models.IntegerField()),
                ('picture', models.FileField(blank=True, null=True, upload_to=b'')),
                ('description', models.TextField(blank=True, null=True)),
                ('min_order_amount', models.IntegerField(default=1)),
                ('license_number', models.CharField(default='234523525342', max_length=50)),
                ('license', models.TextField(blank=True, null=True)),
                ('license_exp', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('operating_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='seller.Seller'),
        ),
    ]
