# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='close_hour',
            field=models.TimeField(default='18:30:00'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='open_hour',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
