# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:21
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='seller',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
