# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20160524_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
