# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20160513_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='city',
        ),
    ]
