# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20160524_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='CONNECTED_STRIPE_ACCOUNT_ID',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='stripe_user_id',
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_name',
            field=models.CharField(default='dan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer_phone',
            field=models.CharField(default='34242352342342', max_length=20),
            preserve_default=False,
        ),
    ]
