# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20160524_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='license_number',
            new_name='permit_number',
        ),
    ]
