# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20160513_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='close_hour',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='seller',
            name='item',
            field=models.CharField(default='Watch', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='min_order_amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='seller',
            name='open_hour',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='seller',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('Dollar', 'Dollar'), ('Cent', 'Cent')], max_length=50, null=True),
        ),
    ]
