# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_auto_20160527_0359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='license_exp',
            new_name='permit_exp',
        ),
    ]
