# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_auto_20160514_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.CharField(default='jason@waff.com', max_length=50),
            preserve_default=False,
        ),
    ]
